---
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jamoranezzi/rsprojects
          searchPaths: ConfigData
        # /home/amorales/IdeaProjects/CursoSpringCloud/ -- para repositorios locales.
        # "native" is used when the native profile is active, for local tests with a classpath repo:
        native:
          searchLocations: classpath:offline-repository/
server:
  port: 8001